### ISSUE TITLE
Version 1.0.1 has `npm` as a dependency

### ISSUE THREAD

**Issue by sharkykh** [samccone/chrome-trace-event#8]
Hi!
The recently published version 1.0.1 has `npm` declared as a direct dependency.
I don't believe this was intended.

`$ diff -u chrome-trace-event-git/package.json chrome-trace-event/package.json`
Where `chrome-trace-event-git` is what is available on this git repository, and `chrome-trace-event` is what I have in my `node_modules` folder.
```diff
--- chrome-trace-event-git/package.json 2019-05-26 06:34:13.000000000 +0300
+++ chrome-trace-event/package.json     2019-05-26 21:57:33.384000000 +0300
@@ -18,6 +18,7 @@
   "main": "./dist/trace-event.js",
   "typings": "./dist/trace-event.d.ts",
   "dependencies": {
+    "npm": "^6.9.0",
     "tslib": "^1.9.0"
   },
   "devDependencies": {
```

**Comment by jaydenseric** [comment]
Suspicious! It's not in the source code:

https://github.com/samccone/chrome-trace-event/blame/master/package.json#L20

Always alarm bells when the source on GitHub is different to what is published on npm.

Also, the link to the package repo and source is not displaying on the npm website:

https://www.npmjs.com/package/chrome-trace-event

I don't know why, since the package `repository` field is there:

https://github.com/samccone/chrome-trace-event/blob/master/package.json#L14

**Comment by samccone** [comment]
thanks for the flag, updating right now.

**Comment by samccone** [comment]
1.0.2 pushed and published.

Thanks all.
